### ISSUE TITLE
[BUG] Failed to build on 0.103.1

### ISSUE THREAD

**Issue by UndeRus** [akopachov/flipper-zero_authenticator#234]
**Describe the bug**
Failed to build app on official firmware 0.103.1

**To Reproduce**
1. Clone repository
2. Clone official flipper firmware
3. Copy "totp" folder to applications_user
4. fbt fap_totp
5. See error

**Expected behavior**
Application built 

**Screenshots**
```CC      applications_user\totp\services\config\config.c
applications_user\totp\services\config\config.c: In function 'totp_config_file_backup_i':
applications_user\totp\services\config\config.c:74:5: error: unknown type name 'DateTime'
   74 |     DateTime current_datetime;
      |     ^~~~~~~~
applications_user\totp\services\config\config.c:75:31: error: passing argument 1 of 'furi_hal_rtc_get_datetime' from incompatible pointer type [-Werror=incompatible-pointer-types]
   75 |     furi_hal_rtc_get_datetime(&current_datetime);
      |                               ^~~~~~~~~~~~~~~~~
      |                               |
      |                               int *
In file included from applications_user\totp\services\config\config.c:5:
targets\furi_hal_include/furi_hal_rtc.h:214:52: note: expected 'FuriHalRtcDateTime *' but argument is of type 'int *'
  214 | void furi_hal_rtc_get_datetime(FuriHalRtcDateTime* datetime);
      |                                ~~~~~~~~~~~~~~~~~~~~^~~~~~~~
applications_user\totp\services\config\config.c:88:29: error: request for member 'year' in something not a structure or union
   88 |             current_datetime.year,
      |                             ^
applications_user\totp\services\config\config.c:89:29: error: request for member 'month' in something not a structure or union
   89 |             current_datetime.month,
      |                             ^
applications_user\totp\services\config\config.c:90:29: error: request for member 'day' in something not a structure or union
   90 |             current_datetime.day,
      |                             ^
cc1.exe: all warnings being treated as errors
        CC      applications_user\totp\ui\scenes\app_settings\totp_app_settings.c
        CC      applications_user\totp\ui\scenes\authenticate\totp_scene_authenticate.c
        CC      applications_user\totp\ui\scenes\generate_token\totp_scene_generate_token.c
        CC      applications_user\totp\ui\scenes\standby\standby.c
        CC      applications_user\totp\ui\ui_controls.c
In file included from applications_user\totp\ui\scenes\authenticate\totp_scene_authenticate.c:5:
build\f7-firmware-D\assets\compiled/assets_icons.h:61:19: error: redundant redeclaration of 'I_DolphinCommon_56x48' [-Werror=redundant-decls]
   61 | extern const Icon I_DolphinCommon_56x48;
      |                   ^~~~~~~~~~~~~~~~~~~~~
In file included from applications_user\totp\ui\scenes\authenticate\totp_scene_authenticate.c:3:
build\f7-firmware-D\.extapps\totp/totp_icons.h:5:19: note: previous declaration of 'I_DolphinCommon_56x48' was here
    5 | extern const Icon I_DolphinCommon_56x48;
      |                   ^~~~~~~~~~~~~~~~~~~~~
        CC      applications_user\totp\workers\bt_type_code\bt_type_code.c
applications_user\totp\ui\scenes\authenticate\totp_scene_authenticate.c: In function 'totp_scene_authenticate_handle_event':
applications_user\totp\ui\scenes\authenticate\totp_scene_authenticate.c:158:47: error: 'I_WarningDolphinFlip_45x42' undeclared (first use in this function); did you mean 'I_WarningDolphin_45x42'?
  158 |             dialog_message_set_icon(message, &I_WarningDolphinFlip_45x42, 83, 22);
      |                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                               I_WarningDolphin_45x42
applications_user\totp\ui\scenes\authenticate\totp_scene_authenticate.c:158:47: note: each undeclared identifier is reported only once for each function it appears in
cc1.exe: all warnings being treated as errors
        CC      applications_user\totp\workers\generate_totp_code\generate_totp_code.c
        CC      applications_user\totp\workers\usb_type_code\usb_type_code.c
        CC      applications_user\totp\workers\type_code_common.c
In file included from applications_user\totp\ui\scenes\standby\standby.c:5:
build\f7-firmware-D\.extapps\totp/totp_icons.h:5:19: error: redundant redeclaration of 'I_DolphinCommon_56x48' [-Werror=redundant-decls]
    5 | extern const Icon I_DolphinCommon_56x48;
      |                   ^~~~~~~~~~~~~~~~~~~~~
In file included from applications_user\totp\ui\scenes\standby\standby.c:3:
build\f7-firmware-D\assets\compiled/assets_icons.h:61:19: note: previous declaration of 'I_DolphinCommon_56x48' was here
   61 | extern const Icon I_DolphinCommon_56x48;
      |                   ^~~~~~~~~~~~~~~~~~~~~
applications_user\totp\ui\scenes\standby\standby.c: In function 'totp_scene_standby_render':
applications_user\totp\ui\scenes\standby\standby.c:10:70: error: 'I_WarningDolphinFlip_45x42' undeclared (first use in this function); did you mean 'I_WarningDolphin_45x42'?
   10 |     canvas_draw_icon(canvas, SCREEN_WIDTH - 50, SCREEN_HEIGHT - 44, &I_WarningDolphinFlip_45x42);
      |                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                      I_WarningDolphin_45x42
applications_user\totp\ui\scenes\standby\standby.c:10:70: note: each undeclared identifier is reported only once for each function it appears in
cc1.exe: all warnings being treated as errors
        CPP     applications_user\totp\app_api_table.cpp
        CC      applications_user\totp\totp_app.c
        CC      build\f7-firmware-D\.extapps\totp\totp_icons.c
        CC      applications_user\totp\lib\base32\base32.c
        CC      applications_user\totp\lib\polyfills\memset_s.c
        CC      applications_user\totp\lib\polyfills\strnlen.c
applications_user\totp\workers\bt_type_code\bt_type_code.c:3:10: fatal error: extra_profiles/hid_profile.h: No such file or directory
    3 | #include <extra_profiles/hid_profile.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
        CC      applications_user\totp\lib\roll_value\roll_value.c
        CC      applications_user\totp\lib\wolfssl\wolfcrypt\src\pwdbased.c
        CC      applications_user\totp\lib\wolfssl\wolfcrypt\src\hmac.c
        CC      applications_user\totp\lib\wolfssl\wolfcrypt\src\hash.c
        CC      applications_user\totp\lib\wolfssl\wolfcrypt\src\sha.c
        CC      applications_user\totp\lib\wolfssl\wolfcrypt\src\sha256.c
        CC      applications_user\totp\lib\wolfssl\wolfcrypt\src\sha512.c
scons: *** [build\f7-firmware-D\.extapps\totp\services\config\config.o] Error 1
        CC      applications_user\totp\lib\wolfssl\wolfcrypt\src\coding.c
scons: *** [build\f7-firmware-D\.extapps\totp\ui\scenes\authenticate\totp_scene_authenticate.o] Error 1
scons: *** [build\f7-firmware-D\.extapps\totp\ui\scenes\standby\standby.o] Error 1
scons: *** [build\f7-firmware-D\.extapps\totp\workers\bt_type_code\bt_type_code.o] Error 1

********** FBT ERRORS **********
build\f7-firmware-D\.extapps\totp\services\config\config.o: Error 1
build\f7-firmware-D\.extapps\totp\ui\scenes\authenticate\totp_scene_authenticate.o: Error 1
build\f7-firmware-D\.extapps\totp\ui\scenes\standby\standby.o: Error 1
build\f7-firmware-D\.extapps\totp\workers\bt_type_code\bt_type_code.o: Error 1```



**Device information (please complete the following information):**
 - Firmware: Official stable
 - Firmware version 0.103.1

**Additional context**
Add any other context about the problem here.

**Comment by akopachov** [comment]
It seems like you have obsolete firmware sources or so, as type `FuriHalRtcDateTime` in firmware was replaced by `DateTime` half a year ago or so.
[Nightly build](https://github.com/akopachov/flipper-zero_authenticator/actions/runs/9609249279/job/26503422158) also seems to be building for Official firmware just fine.
